# Site settings
title: The DC Lab
email: dclab4u@gmail.com
description: > # This means to ignore newlines until "baseurl:"
   The website for the research group of Dr. Pat Schloss at the University
   of SKK in the Department of Microbiology & Immunology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dclab4u.github.io" # the base hostname & protocol for your site
twitter_username: dclab4u
github_username:  dclab4u
array: []

# Build settings
markdown: kramdown

collections:
  project:
    output: true
  members:
    output: true
  papers:
    output: true
  gallery:
    output: true
  researc_area:
    output: true


plugins:
  - jekyll-sitemap
